### ISSUE TITLE
player hitboxes unreasonably small

### ISSUE THREAD

**Issue by fjsifdkdsljnf** [Emarald64/2024-Bullet-hell-game-jam#2]
<img width="325" alt="Screenshot 2024-05-17 at 12 11 12 PM" src="https://github.com/Emarald64/2024-Bullet-hell-game-jam/assets/168043300/100c7c1f-f062-426c-b1c0-d1dc3d516d7b">

**Comment by Emarald64** [comment]
That is intended. It is to make the game more forgiving.
