### ISSUE TITLE
Laser hitboxes

### ISSUE THREAD

**Issue by fjsifdkdsljnf** [Emarald64/2024-Bullet-hell-game-jam#4]
The laser hitbox 
![(_) laser tscn - 2024 Bullet hell jam game - Godot Engine 5_19_2024 8_52_54 PM](https://github.com/Emarald64/2024-Bullet-hell-game-jam/assets/168043300/4dd97987-ce34-4249-a9dd-de8de9c48336)

**Comment by Emarald64** [comment]
The laser is large enough the the hitbox covers the whole screen
